#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class RemoteStockOperation; end

class RemoteStockException < ::Thrift::Exception; end

# Structs are the basic complex data structures. They are comprised of fields
# which each have an integer identifier, a type, a symbolic name, and an
# optional default value.
class RemoteStockOperation
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NAME = 1
  NUMBER = 2

  FIELDS = {
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    NUMBER => {:type => ::Thrift::Types::I32, :name => 'number'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class RemoteStockException < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  MSG = 1
  X = 2

  FIELDS = {
    MSG => {:type => ::Thrift::Types::STRING, :name => 'msg'},
    X => {:type => ::Thrift::Types::DOUBLE, :name => 'x', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

